nodes:
  node1:
    mac_address: "00:1e:67:b2:08:7b"
    ipmi_ip: 10.4.7.2
    ipmi_user: root
    ipmi_pass: root
    cpus: 2
    memory: 2048
    disk: 40
    arch: "x86_64"
    capabilities: "profile:control"
  node2:
    mac_address: "00:1e:67:4f:b7:b1"
    ipmi_ip: 10.4.7.3
    ipmi_user: root
    ipmi_pass: root
    cpus: 2
    memory: 2048
    disk: 40
    arch: "x86_64"
    capabilities: "profile:control"
  node3:
    mac_address: "00:1e:67:4f:cc:f1"
    ipmi_ip: 10.4.7.4
    ipmi_user: root
    ipmi_pass: root
    cpus: 2
    memory: 2048
    disk: 40
    arch: "x86_64"
    capabilities: "profile:control"
  node4:
    mac_address: "00:1e:67:4f:cc:0b"
    ipmi_ip: 10.4.7.5
    ipmi_user: root
    ipmi_pass: root
    cpus: 2
    memory: 2048
    disk: 40
    arch: "x86_64"
    capabilities: "profile:compute"
  node5:
    mac_address: "00:1e:67:4f:b9:55"
    ipmi_ip: 10.4.7.6
    ipmi_user: root
    ipmi_pass: root
    cpus: 2
    memory: 2048
    disk: 40
    arch: "x86_64"
    capabilities: "profile:compute"
