nodes:
  node1:
    mac_address: "54:AB:3A:24:3B:E1"
    pm_type: "pxe_ipmitool"
    ipmi_ip: "192.168.1.20"
    ipmi_user: "admin"
    ipmi_pass: "admin"
    cpus: "32"
    memory: "65536"
    disk: "876"
    arch: "x86_64"
    capabilities: "profile:control"
  node2:
    mac_address: "54:AB:3A:24:3F:AB"
    pm_type: "pxe_ipmitool"
    ipmi_ip: "192.168.1.21"
    ipmi_user: "admin"
    ipmi_pass: "admin"
    cpus: "32"
    memory: "65536"
    disk: "876"
    arch: "x86_64"
    capabilities: "profile:control"
  node3:
    mac_address: "54:AB:3A:24:41:BD"
    pm_type: "pxe_ipmitool"
    ipmi_ip: "192.168.1.22"
    ipmi_user: "admin"
    ipmi_pass: "admin"
    cpus: "32"
    memory: "65536"
    disk: "876"
    arch: "x86_64"
    capabilities: "profile:control"
  node4:
    mac_address: "54:AB:3A:09:8B:83"
    pm_type: "pxe_ipmitool"
    ipmi_ip: "192.168.1.30"
    ipmi_user: "admin"
    ipmi_pass: "admin"
    cpus: "48"
    memory: "131072"
    disk: "928"
    arch: "x86_64"
    capabilities: "profile:compute"
  node5:
    mac_address: "54:AB:3A:09:94:E9"
    pm_type: "pxe_ipmitool"
    ipmi_ip: "192.168.1.31"
    ipmi_user: "admin"
    ipmi_pass: "admin"
    cpus: "48"
    memory: "131072"
    disk: "928"
    arch: "x86_64"
    capabilities: "profile:compute"
