---
patches:
  master:
    undercloud:
      - change-id: I2e0a40d7902f592e4b7bd727f57048111e0bea36
        project: openstack/tripleo-common
      - change-id: Iaa2276aadae351fbc138de258c51d786f69e4395
        project: openstack/tripleo-common
    overcloud:
      - change-id: Ie988ba6a2d444a614e97c0edf5fce24b23970310
        project: openstack/puppet-tripleo
      - change-id: I93e3d355625508fdc42f44bdd358f3ba86fbd8d7
        project: openstack/puppet-tripleo
      - change-id: Id68aa27a8ab08d9c00655e5ed6b48d194aa8e6f6
        project: openstack/nova
        branch: master
  queens:
    undercloud:
      - change-id: I966bf7f6f8d1cbc656abfad59e8bb927e1aa53c2
        project: openstack/tripleo-common
    overcloud:
      - change-id: Ie988ba6a2d444a614e97c0edf5fce24b23970310
        project: openstack/puppet-tripleo
      - change-id: I93e3d355625508fdc42f44bdd358f3ba86fbd8d7
        project: openstack/puppet-tripleo
      - change-id: Id68aa27a8ab08d9c00655e5ed6b48d194aa8e6f6
        project: openstack/nova
        branch: master
