global_params:
  ha_enabled: false

deploy_options:
  sdn_controller: false
  sdn_l3: false
  tacker: false
  congress: false
  sfc: false
  vpn: false
  vpp: true
  dataplane: fdio
  performance:
    Controller:
      vpp:
        uio-driver: uio_pci_generic
    Compute:
      kernel:
        hugepagesz: 2M
        hugepages: 2048
        intel_iommu: 'on'
        iommu: pt
        isolcpus: 1,2
      vpp:
        uio-driver: uio_pci_generic
