---
global_params:
  ha_enabled: true

deploy_options:
  sdn_controller: false
  sdn_l3: false
  tacker: true
  congress: true
  sfc: false
  vpn: false
  dataplane: ovs_dpdk
  performance:
    Controller:
      kernel:
        hugepages: 1024
        hugepagesz: 2M
    Compute:
      kernel:
        hugepagesz: 2M
        hugepages: 2048
        intel_iommu: 'on'
        iommu: pt
      ovs:
        socket_memory: 1024
        pmd_cores: 2
        dpdk_cores: 1
