---
global_params:
  ha_enabled: true

deploy_options:
  containers: true
  os_version: rocky
  sdn_controller: opendaylight
  odl_version: fluorine
  tacker: false
  congress: false
  sfc: true
  vpn: false
