global_params:
  ha_enabled: true

deploy_options:
  sdn_controller: opendaylight
  sdn_l3: false
  odl_version: boron
  tacker: true
  congress: true
  sfc: false
  vpn: false
  vpp: true
  dataplane: fdio
  performance:
    Controller:
      kernel:
        hugepages: 1024
        hugepagesz: 2M
    Compute:
      nova:
        libvirtpin: 1
      kernel:
        hugepagesz: 2M
        hugepages: 4096
        intel_iommu: 'on'
        iommu: pt
