global_params:
  ha_enabled: false

deploy_options:
  sdn_controller: opendaylight
  sdn_l3: true
  odl_version: carbon
  odl_vpp_routing_node: overcloud-novacompute-0
  tacker: true
  congress: true
  sfc: false
  vpn: false
  vpp: true
  dataplane: fdio
  performance:
    Controller:
      kernel:
        hugepages: 1024
        hugepagesz: 2M
        intel_iommu: 'on'
        iommu: pt
        isolcpus: 1,2
      vpp:
        main-core: 1
        corelist-workers: 2
        uio-driver: uio_pci_generic
    Compute:
      kernel:
        hugepagesz: 2M
        hugepages: 2048
        intel_iommu: 'on'
        iommu: pt
        isolcpus: 1,2
      vpp:
        main-core: 1
        corelist-workers: 2
        uio-driver: uio_pci_generic
