---
global_params:
  ha_enabled: true
deploy_options:
  containers: true
  os_version: queens
  sdn_controller: opendaylight
  odl_version: oxygen
  tacker: false
  congress: false
  sfc: false
  vpn: false
