---
global_params:
  ha_enabled: false

deploy_options:
  containers: true
  os_version: master
  sdn_controller: opendaylight
  odl_version: master
  tacker: false
  congress: true
  sfc: false
  vpn: true
